### ISSUE TITLE
xephem segfault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#1]
64 biten szegmentációs hibával rögtön elszáll. 32 biten jó.
A gdb-ben futtatva a vége a következő:

> Warning: Cannot find callback list in XtAddCallback
>Warning: Cannot find callback list in XtAddCallback
>Warning: Cannot find callback list in XtAddCallback

>Program received signal SIGSEGV, Segmentation fault.
>0x00007ffff75c1008 in XtWidgetToApplicationContext () from
/usr/lib/libXt.so.6
(gdb) q

**Comment by attuska** [comment]
A rengeteg XtAddCallback warning előtt egy rakás ilyen is van:

> Warning: 
    Name: LogoLabel
    Class: XmLabel
    Illegal left attachment

**Comment by rezso** [comment]
Az openmotif viszont nem fér össze a lesstif-fel, szóval azokat is meg kell nézni.

**Comment by rezso** [comment]
Megcsináltam az xephem-et és a ddd-t openmotif-fal. Ha jó, megy az ub is a gitbe.

**Comment by attuska** [comment]
Működik, jó, ubék után zárható az issue.

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk2/commit/4075764eebca067381a1633bdac5b8aa7ace7791
