### ISSUE TITLE
gshogi nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#12]
>attila@attila-pc:~$ gshogi
Traceback (most recent call last):
  File "/usr/bin/gshogi", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
attila@attila-pc:~$

**Comment by rezso** [comment]
python-setuptools

**Comment by attuska** [comment]
python3-setuptools a jó.
