### ISSUE TITLE
clamz gondok

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#13]
GNOME3 alatt nincs desktop, a /usr/share/application/clamz.desktop ellenére.

> [Desktop Entry]
Encoding=UTF-8
Name=Clamz MP3 Downloader (command-line)
Comment=Download MP3 files from AmazonMP3.com
Exec=clamz
Terminal=true
Type=Application
Categories=Network;
MimeType=audio/x-amzxml;
NoDisplay=true

Parancssorból sem lehet használni semmire sem. Arch-Linux AUR-ban van még ilyen.
https://aur.archlinux.org/packages/clamz/
Meg kell nézni, hogy talán mégis lehet használni valamire, ha nem, ki kell dobni szerintem az egész csomagot.
A desktop -ot mindenképp.

A section nem jó, mert ez multimédiás cucc inkább, mint internetes.

**Comment by rezso** [comment]
Amazon-ról mp3-at letölteni csak USA vagy Kanada területéről lehet.
A desktop fájl NoDisplay=true értéke pedig egyértelműen jelzi, hogy nem megjelenítendő. Ilyen desktop fájlt jellemzően autostarthoz szoktak készíteni.

**Comment by attuska** [comment]
Ez is megérett a kukára. Szerintem.

**Comment by attuska** [comment]
Kuka!
https://github.com/uhulinux/ub-ubk2/commit/2689a8b105a32b90bf7b6e05051755ab98dd184c
