### ISSUE TITLE
emesene

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#14]
Maga a csomag elkészül, de nem indul.

> attila@attila-pc:~$ emesene
Traceback (most recent call last):
  File "/usr/bin/emesene", line 34, in <module>
    emesene.main()
AttributeError: 'module' object has no attribute 'main'
attila@attila-pc:~$ 

Kell ez a csevegő egyáltalán még? Az MSN már nem használatos.

**Comment by rezso** [comment]
Az MSN nem egyszerűen nem használatos, hanem meg is szűnt.
