### ISSUE TITLE
htdig permission

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#16]
> attila@attila-pc:~$ htdig
>DB2 problem...: /var/www/htdig/db.docs.index: Permission denied
>DocumentDB::Open: /var/www/htdig/db.docs.index Permission denied
>htdig: Unable to open/create document database '/var/www/htdig/db.docdb'
>
>attila@attila-pc:~$

**Comment by attuska** [comment]
ubk1 is.

**Comment by attuska** [comment]
ubk2: https://github.com/uhulinux/ub-ubk2/commit/964599bb71dc91b360d775e9b103726b04f465e9

Ezt ubk1-re is meg lehetne csinálni, de lenne értelme?

A jogok megoldva, de számomra érthetetlen, mire is lehetne ezt használni, a mai világban?

> attila@attila-pc:/var$ htdig -v
>ht://dig Start Time: Mon Mar 12 20:55:02 2018
>
>New server: www.htdig.org, 80
>ht://dig End Time: Mon Mar 12 20:55:02 2018
>attila@attila-pc:/var$ 

A www.htdig.org, ami config fájlban van elérhetetlen. Létezik még ez egyáltalán?

> attila@localhost:~$ ping htig.org
ping: unknown host htig.org
attila@localhost:~$

Lezárható ez az issue így?

**Comment by rezso** [comment]
Saját weboldalakra kereső, intraneten. Kb. egy lokális mini-google. Felesleges szerintem.

**Comment by attuska** [comment]
Szerintem maradjon így, ahogy most van, mert hátha van olyan elvetemült, aki mégis használni akarja. Az ilyen meg úgyis el fog vele boldogulni, ahogyan most van, majd beleássa magát és megszerkesztgeti a konfigjait magának.
