### ISSUE TITLE
deluge nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#2]
Python hiányok miatt el sem indul.

> ImportError: No module named constantly
>[ERROR   ] 18:54:27 ui:172 There was an error whilst launching the
request UI: gtk
>[ERROR   ] 18:54:27 ui:173 Look at the traceback above for more
information.

**Comment by attuska** [comment]
Egy python-constantly csomaggal megetetve már újabb gondja van.

> ImportError: cannot import name certificate_transparency
[ERROR   ] 21:55:57 ui:172 There was an error whilst launching the
request UI: gtk
[ERROR   ] 21:55:57 ui:173 Look at the traceback above for more
information.

**Comment by attuska** [comment]
A python-enum34_1.1.6-1.1_amd64.ubk.uhu létrehozása után sem megy.

**Comment by rezso** [comment]
Úgy tűnik, a python-cryptography igényel még pár cuccot.
Mindkét python (2 és 3) esetében: asn1crypto (https://github.com/wbond/asn1crypto)
Csak python 2-nél még: enum34 és ipaddress (https://github.com/phihag/ipaddress) is. Python 3 esetében ezek nem kellenek, a 3.3-tól illetve 3.4-től az alap python részei.

**Comment by attuska** [comment]
Úgy néz ki, hogy már elindul.
Ezek vannak feltelepítve:

> deluge_1.3.15-1.2_amd64.ubk.uhu
pyopenssl_17.5.0-1.2_amd64.ubk.uhu
python-asn1crypto_0.24.0-1.1_amd64.ubk.uhu
python-constantly_15.1.0-1.1_amd64.ubk.uhu
python-cryptography_2.1.4-1.2_amd64.ubk.uhu
python-enum34_1.1.6-1.1_amd64.ubk.uhu
python-ipaddress_1.0.19-1.1_amd64.ubk.uhu

Alakul, de úgy fest, hogy még kell egy python-service-identity csomag is, hogy teljesebb legyen.

> attila@attila-pc:~$ deluge
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
[ERROR   ] 08:34:35 torrentmanager:735 Unable to backup /home/attila/.config/deluge/state/torrents.state to /home/attila/.config/deluge/state/torrents.state.bak: [Errno 2] Nincs ilyen fájl vagy könyvtár
attila@attila-pc:~$

**Comment by attuska** [comment]
Rajta vagyok. Undorító ez a python tömeg, jól át kell néznem valamennyit.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk2/commit/c5884cb3bae65640dea56da8079e0a625854e17f
