### ISSUE TITLE
foxit amd64

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#21]
> attila@attila-pc:/usr/share/foxit$ file FoxitReader
FoxitReader: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.9, BuildID[sha1]=042eb

**Comment by attuska** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=foxitreader

**Comment by rezso** [comment]
Egyébként kell ez nekünk? Mit tud, amit a többi open source pdf olvasó nem?

**Comment by attuska** [comment]
Nekem végképp nem kell, talán nem véletlen, hogy az Arch fő reójában nincs is benne, csak az Aur -ban.
Szerintem, akkor kuka.

**Comment by rezso** [comment]
https://github.com/uhulinux/ub-ubk2/commit/b9c67cd5c1a341d51398ce9a65b8fd5f48c18501
