### ISSUE TITLE
gnucash nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#22]
> attila@attila-pc:~$ gnucash
ERROR: In procedure dynamic-link:
ERROR: file: "libgnc-core-utils", message: "file not found"
attila@attila-pc:~$

**Comment by rezso** [comment]
https://bugs.mageia.org/show_bug.cgi?id=4882

**Comment by attuska** [comment]
Rossz volt a split.
https://github.com/uhulinux/ub-ubk2/commit/513a39c84a8d799ea7db8f2f454d4840e0799155
