### ISSUE TITLE
bashstyle-ng nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#26]
> ttila@attila-pc:~$ bashstyle

BashStyle-NG Version 10.3 starting
Lockfile does exist but the process with that pid is no
longer running, removing lockfile of old process: 24718
LoadConfig: no vendor configuration found, using factory defaults.
CheckConfig: User configuration up-to-date.
FixUpConfig: checking for outdated values.
Traceback (most recent call last):
  File "/usr/share/bashstyle-ng/ui/bs-ng.py", line 338, in <module>
    hwg = BashStyleNG()
  File "/usr/share/bashstyle-ng/ui/bs-ng.py", line 332, in __init__
    suui.InitStartupUI()
  File "/usr/share/bashstyle-ng/ui/configui.py", line 123, in InitStartupUI
    if config.CheckBashStyle() == False:
  File "/usr/share/bashstyle-ng/ui/config.py", line 207, in CheckBashStyle
    rc = open(os.path.expanduser("~/.bashrc"), "r")
FileNotFoundError: [Errno 2] Nincs ilyen fájl vagy könyvtár: '/home/attila/.bashrc'
attila@attila-pc:~$

**Comment by rezso** [comment]
Nincs ~/.bashrc. Csinálni kell egyet, csomagból nem nyúlunk a /home alá. Max. postinst.
De a bashstyle-ng nézhetné az /etc/bashrc-t is.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk2/commit/078e65ae2a3681f67d9b6878fae495af11844040

**Comment by rezso** [comment]
Ez nem closed. A megoldásod ugyanis többet árt, mint használ.

**Comment by rezso** [comment]
Valami ilyesmire gondoltam:

if [ ! -f ~/.bashrc ];then
   cat > ~/.bashrc <<END
# generated by bashstyle-ng
# keep the sourcing /etc/bashrc
source /etc/bashrc

END
fi

Így a bashstyle-ng is boldog lenne, és az /etc/bashrc sem lenne figyelmen kívül hagyva.
A külön, ~/.bashrc létrehozásának előnye, hogy a bashstyle-ng tudná írni is, ha kell neki ilyen lehetőség.

**Comment by attuska** [comment]
Ez a bashtyle-ng amúgyis mindig írkálgat a ~/ alá, én úgygondoltam, ha talál egy tök üreset, írkáljon abba. Írt is.

**Comment by attuska** [comment]
Megcsinálom az ajánlásod szerint és kipróbálom.
