### ISSUE TITLE
clamtk nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#27]
> attila@attila-pc:~$ clamtk
Can't locate Try/Tiny.pm in @INC (you may need to install the Try::Tiny module) (@INC contains: /usr/lib/perl5/site_perl/5.26.1/i386-linux-thread-multi-ld /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/i386-linux-thread-multi-ld /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/i386-linux-thread-multi-ld /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl /usr/lib/perl5/vendor_perl) at /usr/lib/perl5/site_perl/5.26.1/LWP/Protocol.pm line 11.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.26.1/LWP/Protocol.pm line 11.
Compilation failed in require at /usr/lib/perl5/site_perl/5.26.1/LWP/UserAgent.pm line 13.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.26.1/LWP/UserAgent.pm line 13.
Compilation failed in require at /usr/lib/perl5/vendor_perl/5.26.1/ClamTk/Analysis.pm line 20.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/5.26.1/ClamTk/Analysis.pm line 20.
Compilation failed in require at /usr/bin/clamtk line 22.
BEGIN failed--compilation aborted at /usr/bin/clamtk line 22.
attila@attila-pc:~$

**Comment by rezso** [comment]
perl-try-tiny

**Comment by attuska** [comment]
Ez ide kell, ubk1-re még nem kellett.
Ma már nem lesz meg, majd holnap.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk2/commit/908c0ff95fb682018aec27811e642d89660804c8
