### ISSUE TITLE
electrum nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#28]
> attila@attila-pc:~$ electrum
Error: No module named pyaes. Try 'sudo pip install <module-name>'
attila@attila-pc:~$

**Comment by rezso** [comment]
https://pypi.python.org/pypi/pyaes/1.6.1

**Comment by attuska** [comment]
Kevés.
A python-socks is kellene neki. Ha meg befrissítemém az electrum csodát, még egy rakás egyéb is kellene még.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk2/commit/5dfe3d96be80d1a4c599d0ff83d064173ca1ca09
Nem frissítem, mert baromi sok újabb python3 kellene neki. Ráér.
