### ISSUE TITLE
calibre katagória?

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#41]
Desktop:

> Categories=Office;Database;FileTools;Viewer;Qt;

Package:

> Section: Applications/Typesetting

Egyszem maga van ebben a szekcióban.

**Comment by attuska** [comment]
Amúgy sem indul.

>   File "/usr/lib/calibre/calibre/ebooks/conversion/search_replace.py", line 7, in <module>
    import regex
ImportError: No module named regex

**Comment by rezso** [comment]
vagy az 'import regex' helyett kell az 'import re', ami a python saját regexp modulja, vagy ez kell neki: https://pypi.python.org/pypi/regex/

**Comment by attuska** [comment]
UBK1 -en is rossz.

**Comment by attuska** [comment]
Megoldva.
https://github.com/uhulinux/ub-ubk2/commit/5e69334df9a7713670fbb299b80b7544e23ef289
