### ISSUE TITLE
qtwebengine vs nouveau

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#44]
https://koji.fedoraproject.org/koji/buildinfo?buildID=1016060

Állítólag megoldották a qtwebengine használhatóságát nouveau meghajtó esetén.
Ezzel állítólag már nem omlanak össze a kmail, konqueror, otter-browser és társai nouveau esetén, így az nvidi tulajdonosok is használhatnák nyílt grafikus meghajtóval.

Ez ubk1 esetén is jó lenne, de ott biztos kissé komplikáltabb lenne már.

**Comment by rezso** [comment]
Nálunk is 5.10.0-s qtwebengine van.

**Comment by attuska** [comment]
Igen, de ők megoldották állítólag, lehet, hogy valamilyen foltot át kellne venni hozzá.
De megnézem a 64 biten.

**Comment by attuska** [comment]
64 bites ubk2 -n jó minden. Itt le is zárom, de ubk1 -en ettől még nem jó.

**Comment by rezso** [comment]
Mármint a wrapper scriptek nélkül jók? Mert akkor azok feleslegesek.

**Comment by attuska** [comment]
Csak egyben van. https://github.com/uhulinux/ub-ubk2/blob/f8702c119b142377c250cc53f64065211c5fd953/qupzilla/addons/usr/bin/qupzilla

Engem nem zavar, de ha az otter-browser is jó, akkor ez itt már felesleges. UBK1 -en viszont nem !

**Comment by attuska** [comment]
Az otter sem jó nouveauval!

**Comment by attuska** [comment]
Kiszedem  qupzilla -ból, csak abban van, de nélküle is jó.

**Comment by rezso** [comment]
A Qupzilla most már Falkon néven fut, mint kde-s projekt:
https://download.kde.org/stable/falkon/
