### ISSUE TITLE
Live cd problema

### ISSUE THREAD

**Issue by Soldy** [uhulinux/ub-ubk2#46]
Probaltam tesztelni qemu ba a 64 bites verziot.. A dbus indulsa utan elindul az x ... vagyis csak tenne mert azonnal meghal a rendszer. Egy ilyen kepernyovel.
![uhu](https://user-images.githubusercontent.com/4786022/38008842-94f2a71a-3240-11e8-8b6b-c997a4b35863.png)

**Comment by attuska** [comment]
Mennyi memóriát adtál neki? Virtuális gépben minimum 2 Gb kell neki, de lehet, hogy több.

**Comment by Soldy** [comment]
1. mindig 4 gigat adok alap hangon tesztelesnek. Bar beprobaltam anno 8 al (ez eleg irrealis elvaras lenne) 
2, szoktam valtogatni a video biost. De nomodeset et is probaltam mind 32 mind 64 biten is. A tenyleges video hardware hez mar csak azert se adok hozzaferest mert a vps -eket vnc n at nezem. Mivel 3 video biost is probaltam (qxl, vmware,  std) feladtam. Ma megneztem cirrussal is. Azzal ment. DirectFramebuffert ha tesztek bele az megoldja... nem tudom van-e.

**Comment by attuska** [comment]
Valami biztosan kellene még a quemunak az isóra, ami nincs most rajta.

**Comment by Soldy** [comment]
itt a xorg log debianbol elvileg fbdevhw-t + glamoregl-t hasznal alap helyzetben...
[Xorg.0.log](https://github.com/uhulinux/ub-ubk2/files/1882750/Xorg.0.log)
A debian x hez ezek a modulok tartoznak : amdgpu_drv.so  ati_drv.so  fbdev_drv.so  intel_drv.so  modesetting_drv.so  nouveau_drv.so  qxl_drv.samdgpu_drv.so  ati_drv.so  fbdev_drv.so  intel_drv.so  modesetting_drv.so  nouveau_drv.so  qxl_drv.so  radeon_drv.so  vesa_drv.so  vmware_drv.so
o  radeon_drv.so  vesa_drv.so  vmware_drv.so

**Comment by Soldy** [comment]
Es itt van az uhu xorg log ja ...
[Xorg.log](https://github.com/uhulinux/ub-ubk2/files/1882761/Xorg.log)
Az uhu x hez tartozo driverei : 
ati_drv.so  i128_drv.so  i740_drv.so  intel_drv.so  modesetting_drv.so  nouveau_drv.so  openchrome_drv.so  radeon_drv.so  vesa_drv.so

**Comment by attuska** [comment]
Van fbdev drájverünk, belőle csomag is.
https://github.com/uhulinux/ub-ubk2/tree/efaf2e34849f0620e5c93e2ad281a7c48540ef6f/x.org-video-fbdev
A live isón is ott van, az isó generátor felteszi. Az már más kérdés, hogy az xorg-server ezt miért nem leli?

**Comment by attuska** [comment]
Valami nagyon nem gömbölyű az általad próbált isón!

Az én Xorg.0.log részem:

> [    23.966] (II) LoadModule: "fbdev"
[    23.966] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[    24.003] (II) Module fbdev: vendor="X.Org Foundation"
[    24.003] 	compiled for 1.19.6, module version = 0.4.4
[    24.003] 	Module class: X.Org Video Driver
[    24.003] 	ABI class: X.Org Video Driver, version 23.0
[    24.003] (II) LoadModule: "vesa"


A tied:

> [    14.309] (II) LoadModule: "fbdev"
[    14.309] (WW) Warning, couldn't open module fbdev
[    14.309] (II) UnloadModule: "fbdev"
[    14.309] (II) Unloading fbdev
[    14.309] (EE) Failed to load module "fbdev" (module does not exist, 0)
[    14.309] (II) LoadModule: "vesa"

Miért van nálam /usr/lib/xorg/modules/drivers/fbdev_drv.so ?
És nálad miért nincs, vagy ha van, miért nem tud betöltődni ?
Vagy nincs, vagy rossz, vagy valami mekadályozza.

**Comment by Soldy** [comment]
En a telepitett rendszerrol masoltam ki a fileokat.. a cd-n ottt az fbdev most lecsekkoltam... De az meg cirrussal indult el csak (az ok hogy a kernelbe viszont nincs benne a megfelelo framebuffer driver tippem szerint) a i386 os lemez driverei : 
-rwxr-xr-x 1 root root   40816 Jan  6 03:23 apm_drv.so
-rwxr-xr-x 1 root root   22156 Jan  6 03:24 ark_drv.so
-rwxr-xr-x 1 root root  122472 Jan  6 03:24 ast_drv.so
-rwxr-xr-x 1 root root   11416 Jan 21 06:28 ati_drv.so
-rwxr-xr-x 1 root root  130156 Jan  6 03:25 chips_drv.so
-rwxr-xr-x 1 root root   36288 Jan  6 03:26 cirrus_alpine.so
-rwxr-xr-x 1 root root   17304 Jan  6 03:26 cirrus_drv.so
-rwxr-xr-x 1 root root   31712 Jan  6 03:26 cirrus_laguna.so
-rwxr-xr-x 1 root root   22548 Jan  6 03:26 dummy_drv.so
-rwxr-xr-x 1 root root   27260 Jan  6 03:49 fbdev_drv.so
-rwxr-xr-x 1 root root  154348 Jan  6 03:40 glint_drv.so
-rwxr-xr-x 1 root root   61764 Jan  6 03:28 i128_drv.so
-rwxr-xr-x 1 root root   55576 Jan  6 03:29 i740_drv.so
-rwxr-xr-x 1 root root 1989108 Jan 21 06:30 intel_drv.so
-rwxr-xr-x 1 root root  109600 Jan  6 14:35 modesetting_drv.so
-rwxr-xr-x 1 root root  250820 Jan 21 06:32 nouveau_drv.so
-rwxr-xr-x 1 root root  184756 Jan  6 03:47 nv_drv.so
-rwxr-xr-x 1 root root  534312 Jan 21 06:28 radeon_drv.so
-rwxr-xr-x 1 root root   45436 Jan  6 03:31 rendition_drv.so
-rwxr-xr-x 1 root root  127908 Jan  6 03:33 siliconmotion_drv.so
-rwxr-xr-x 1 root root  630936 Jan  6 03:42 sis_drv.so
-rwxr-xr-x 1 root root   90636 Jan  6 03:33 sisusb_drv.so
-rwxr-xr-x 1 root root   21332 Jan  6 03:38 v4l_drv.so
-rwxr-xr-x 1 root root   31864 Jan  6 03:49 vesa_drv.so

A 64 bites : 

-rwxr-xr-x 1 root root   43176 Jan  6 11:15 apm_drv.so
-rwxr-xr-x 1 root root   24128 Jan  6 11:15 ark_drv.so
-rwxr-xr-x 1 root root  125848 Jan  6 11:15 ast_drv.so
-rwxr-xr-x 1 root root   12584 Jan 20 11:12 ati_drv.so
-rwxr-xr-x 1 root root  121088 Jan  6 11:15 chips_drv.so
-rwxr-xr-x 1 root root   38456 Jan  6 11:15 cirrus_alpine.so
-rwxr-xr-x 1 root root   23064 Jan  6 11:15 cirrus_drv.so
-rwxr-xr-x 1 root root   33920 Jan  6 11:15 cirrus_laguna.so
-rwxr-xr-x 1 root root   24576 Jan  6 11:15 dummy_drv.so
-rwxr-xr-x 1 root root   29568 Jan  6 11:15 fbdev_drv.so
-rwxr-xr-x 1 root root  147408 Jan  6 11:15 glint_drv.so
-rwxr-xr-x 1 root root   64216 Jan  6 11:15 i128_drv.so
-rwxr-xr-x 1 root root   58576 Jan  6 11:15 i740_drv.so
-rwxr-xr-x 1 root root 1820024 Jan 20 11:12 intel_drv.so
-rwxr-xr-x 1 root root  110856 Jan  6 14:35 modesetting_drv.so
-rwxr-xr-x 1 root root  241432 Jan 20 11:12 nouveau_drv.so
-rwxr-xr-x 1 root root  193736 Jan  6 11:15 nv_drv.so
-rwxr-xr-x 1 root root  539368 Jan 20 11:12 radeon_drv.so
-rwxr-xr-x 1 root root   47872 Jan  6 11:15 rendition_drv.so
-rwxr-xr-x 1 root root  127968 Jan  6 11:15 siliconmotion_drv.so
-rwxr-xr-x 1 root root  591224 Jan  6 11:15 sis_drv.so
-rwxr-xr-x 1 root root   88680 Jan  6 11:15 sisusb_drv.so
-rwxr-xr-x 1 root root   22968 Jan  6 11:15 v4l_drv.so
-rwxr-xr-x 1 root root   34248 Jan  6 11:15 vesa_drv.so

Azt nem tudod miert nem megy a tty0 ??? :P

**Comment by attuska** [comment]
Szerintem amd gpu-val biztos, hogy nem indult eddig, most fedeztük fel.
https://github.com/uhulinux/ub-ubk2/commit/000e66da1494b381b4214f937376680d85d5f250
Most már újabb isó lesz, amivel remélhetőleg le lehet zárni ezt a hibajegyet.

**Comment by Soldy** [comment]
AAzt hogy csinaltattok hogy az amd64 700 megaval kisebb mint az i386 ? 
Megnezem mindjart qemuval...

**Comment by attuska** [comment]
A 64 bites "tiszta" 64 bites, nincs benne 32 bites glibc.
Csak 64 bites kernel van benne, a 32 bitesben meg dupla van, 32 és 64 bites is.

**Comment by attuska** [comment]
Egy hónapja nincs válasz, szerintem már jó.
Lezárom. Ha mégsem jó, újra lehet nyitni!
