### ISSUE TITLE
xemacs

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#5]
Ez hasonló a vile issue -hez.

> attila@attila-pc:~$ xemacs
Warning: Missing charsets in String to FontSet conversion
attila@attila-pc:~$

**Comment by attuska** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=816658#c1
http://tracker.xemacs.org/XEmacs/its/issue650

**Comment by attuska** [comment]
A locale nem jó.

> attila@localhost:~$ xemacs
Warning: Missing charsets in String to FontSet conversion
Warning: Missing charsets in String to FontSet conversion
attila@localhost:~$ locale
LANG=hu_HU.UTF-8
LC_CTYPE="hu_HU.UTF-8"
LC_NUMERIC="hu_HU.UTF-8"
LC_TIME="hu_HU.UTF-8"
LC_COLLATE="hu_HU.UTF-8"
LC_MONETARY="hu_HU.UTF-8"
LC_MESSAGES="hu_HU.UTF-8"
LC_PAPER="hu_HU.UTF-8"
LC_NAME="hu_HU.UTF-8"
LC_ADDRESS="hu_HU.UTF-8"
LC_TELEPHONE="hu_HU.UTF-8"
LC_MEASUREMENT="hu_HU.UTF-8"
LC_IDENTIFICATION="hu_HU.UTF-8"
LC_ALL=
attila@localhost:~$ export LC_ALL=C
attila@localhost:~$ locale
LANG=hu_HU.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
attila@localhost:~$ xemacs
attila@localhost:~$ 

 Vagy általánossá kell tenni az LC_all=C beállítást, vagy ezzel indítani a progit.
A vile  (#4) esetén is hasonló lehet a megoldás
Mi legyen?

**Comment by rezso** [comment]
Előbb dobom ki a vile-val együtt, mint hogy rendszerszinten LC_ALL=C legyen a locale.
Van épp elég konzolos szerkesztő.

**Comment by attuska** [comment]
Én benne vagyok, van bőven szövegszerkesztőnk.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk2/commit/899cfd9439d98641c1b9489dcc316a4e80a1a64d
