### ISSUE TITLE
UEFI

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#57]
UEFI lehetőségű BIOS esetén, az UHU most csak az UEFI BIOS kikapcsolásával, "legacy" módban telepíthető, mert csakis így bootolható a telepítő live iso.
A telepített UHU grub.cfg ekkor nem tartalmazza a windows indítási lehetőségét, a windows csak UEFI BIOS módban indítható, akkor viszont a grub nem indul.
1. Legacy módban indítható legyen az UEFI módban telepített windows, legyen a grub.cfg -ben számára bejegyzés.
2. Legyen indítható az isó bekapcsolt UEFI BIOS esetén is.
3. A grub telepedjen a windows rendszerbetöltőjének helyére UEFI módban indítva.
3. A grub.cfg tartalmazzon minden telepített rendszer menüpontját és azok induljanak is.

**Comment by attuska** [comment]
Az opensuse állítólag felfedezi a win-t és az uhu -t is.
Leszedtem az opensuse grub2-2.02~beta2-265.1.src.rpm fájlt, kicsomagoltam és elborzadtam.
Csak 96 darab patch van benne kezdetnek.
Kemény meccsnek ígérkezik, el kellene nagyon a segítség. Főleg, mivel rendszer alapról, indítóról van szó, melynek muszáj jól működnie.

**Comment by rezso** [comment]
Miért a 2.02~beta2-t, amikor 2.02 release van nálunk?
Miért a SUSE src rpm-et nézed, ha az Arch pkgbuild alapján készült a grub?
Amúgy a SUSE is és az Arch is ezt használja a grub mellett az UEFI-hez:
https://github.com/rhboot/efibootmgr
aminek ez is kell:
https://github.com/rhboot/efivar

**Comment by attuska** [comment]
Az Arch mostani leutánzottja már megleli az Csabi win10 -ét, már jobb, mint ami van, nálam működik, mint a régi, de Csabinál  a grub-install nem leli az efibootmgr parancsot. A Suse-ja mindent meglel, még az UBK2 -t is.
A SuSe -t abbameghagytam, mert rájöttem, hogy régi a leszedett rpm forrása.. Leklónoztam a mostani fedora grub2 gittjét, az még szörnyetegebb. Csak 265 darap patch van benne, de ezt megcsinálni egy rémületnek néz ki.
Az efibootmgr és az efivar majd biztosan kell.

**Comment by attuska** [comment]
A syslinux sem jó, mert az UEFI módban indított masina nem észleli bootolható eszközként azt, amire a telepetítő syslinux -os isónk lett kiírva.
A sylinux csomagunk nem tartalmaz efi32 és efi64 mappákat.

**Comment by attuska** [comment]
Már van UBK2 -n a syslinuxban efi32 és efi64.
https://github.com/uhulinux/ub-ubk2/commit/ad0a0bc0fff0316501b0c4f062715c6b221ade88
Tesztelni csak új isóval lehet UEFI -s gépen.

**Comment by attuska** [comment]
Az UBUNTU isóját letöltöttem, kipróbáltam. Maga a kibontott isó tartalmaz syslinux, boot, EFI, casper mappákat a többi sallang mellett. Van a kibontatlan isó gyökerében három, ISO9660, El Torito Boot, El Torito BootJoilet Level 3 nevű mappa, az ISO9660 -ban ugyanazok, mint a kibontottban.
Ez a három a miénkben is van.

A casper mappában vannak az uborka live rendszer vmlinuz, initrd és filesystem,squashfs fájljai.

A boot mappában csak grub mappa van, benne grub.cfg, efi.img fájlok, meg egy x86_64-efi mappa, benne a grub moduljai.

Van a gyökérben egy  EFI/BOOT mappa, benne kettő, BOOTx64.EFI és grubx64.efi nevű fájl.

A gyökérben lévő isolinux mappában pár darab *.c32 fájl, az isolinux.cfg fájl, mely egy rakás cfg -t inklúdol, ott van az isolinux.bin  és még temérdek nyelvi fájl.

A többi mappa érdektelen számunkra.

Maga a pendrájvra írt isó a BIOS rendszeremen egy UBUNTU splash -al örvendeztet, majd megjelenik az UBUNTU installer, mely tulajdonképpen a calamares, ezt az ablakot becsukva a fertelmes UNITY live felület.
A z EFI UBUNTI install wiki szerint UEFI gépeken a grub menü jelentkezik, melyből választható az installálás, vagy a kipróbálás.

**Comment by attuska** [comment]
Várjuk a próbát az új grub alapú isókkal azoktól, akiknek van UEFI bios-al rendelkező gépük.

**Comment by attuska** [comment]
https://github.com/uhulinux/cdgen-ubk/issues/2
