### ISSUE TITLE
usr/lib/apr/libtool failed

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#58]
Az apache-mod-wsgi se újra nem fordítható, se nem frissíthető.
( Más sem, ami az apr build libtoolt használja.)

>/usr/lib/apr/build/libtool: sor: 1752: x86_64-gnu-linux-gcc: parancs nem található

A /usr/lib/apr/build/libtool 168.sorában ez áll:
>LTCC="x86_64-gnu-linux-gcc"

Újraforgatva az apr csomagot ez a sor már ilyen:
>LTCC="x86_64-linux-gnu-gcc"

Ellenben ez még kevés, mert a hiba továbbra is fennáll.
>/usr/lib/apr/build/libtool: sor: 1752: x86_64-gnu-linux-gcc: parancs nem található

Igaza van, mert csak x86_64-gnu-linux-gcc van.
Fogalmam sincs, hogy az úraforgatott libtool miért keres továbbra is már nem létezőt.

**Comment by attuska** [comment]
Az apache-mod-dnssd is.
>/usr/lib/apr/build/libtool: sor: 1752: x86_64-gnu-linux-gcc: parancs nem található

**Comment by attuska** [comment]
Teljesen új chrootban is elhasal. Nem jól működik az apr libtool újabban, még mindig a régi gcc -t keresi.

**Comment by attuska** [comment]
UBK1/64: x86_64-gnu-linux-gcc van, semmi gond.
UBK3: x86_64-linux-gnu-gcc van, semmi gond.
UBK2: x86_64-linux-gnu-gcc van, de hiába, mert nem ezt keresi az apr libtool.

**Comment by rezso** [comment]
apr-util és apache újrafordítás után jó.
