### ISSUE TITLE
pysol karakterhibák

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#6]
A pysol menüiben fekete csíkok vannak.

![pysolkarakterek](https://user-images.githubusercontent.com/6311614/37240184-62af3aa8-2448-11e8-8eaf-bd4e40c8ecb5.jpg)

Az oldalsávban meg teljesen hiányoznak a karakterek
![pysol](https://user-images.githubusercontent.com/6311614/37240192-7f921b72-2448-11e8-80a6-dc94febe2adc.jpg)

**Comment by rezso** [comment]
Ennek is kellene a python-tkinter, plusz egy patch a pithon-pillow miatt.

**Comment by attuska** [comment]
Jó lenne, ezt nem szívesen hajítanám ki, mert igen jó pasziánsz gyűjtemény. A kedvéért még a python-tkinter -t is vissza hoznám.

**Comment by rezso** [comment]
No az nem lesz egyszerű:
https://bugs.python.org/issue31817
https://bugs.python.org/issue25247

**Comment by rezso** [comment]
Ez után hogyan működik?
https://github.com/uhulinux/ub-ubk2/commit/25ec0ce809edd437aef510c3516a0e7bdff4f02e

(Először a python csomagot frissítsd, utána a pysolfc-t, mert a python és a python-tkinter ütközni fog, az átkerült lib-tk miatt.)

**Comment by attuska** [comment]
Nem működik sehogyan sem.

> attila@attila-pc:~$ pysol
Traceback (most recent call last):
  File "/usr/bin/pysol", line 37, in <module>
    from pysollib.main import main  # noqa: E402
  File "/usr/lib/python2.7/site-packages/pysollib/main.py", line 35, in <module>
    from pysollib.app import Application
  File "/usr/lib/python2.7/site-packages/pysollib/app.py", line 43, in <module>
    from pysollib.pysolrandom import PysolRandom
  File "/usr/lib/python2.7/site-packages/pysollib/pysolrandom.py", line 29, in <module>
    import random2
ImportError: No module named random2
attila@attila-pc:~$

**Comment by attuska** [comment]
Már jobb, most már később akad el. Ez biztosan könyebben orvosolható egy folttal.
> attila@attila-pc:~$ pysol
Traceback (most recent call last):
  File "/usr/bin/pysol", line 42, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python2.7/site-packages/pysollib/main.py", line 415, in main
    r = pysol_init(app, args)
  File "/usr/lib/python2.7/site-packages/pysollib/main.py", line 197, in pysol_init
    app.dataloader = DataLoader(args[0], f)
  File "/usr/lib/python2.7/site-packages/pysollib/util.py", line 125, in __init__
    str(filenames))
OSError: /usr/bin/pysol: DataLoader could not find ('html/license.html',)
attila@attila-pc:~$

**Comment by attuska** [comment]
Kell neki a /usr/share/PysolFC mappába a html és cardsets is.

**Comment by attuska** [comment]
Elindul, de kell neki egy folt, hogy a souceforge-ről letöltött cardsets készletet, amit a data/cardsets mappába csomagol ki az acqure, fel is telepítse a setup.py. A data mappába meg bele kell másolni at html cuccot a setup.py hívása előtt.
Hangja is van.
Ez azért már jobban néz ki.
![pysol](https://user-images.githubusercontent.com/6311614/37372814-6e424008-2714-11e8-988c-5c0e77035f3f.png)

**Comment by rezso** [comment]
Azért ennyire nem bonyolult :)
https://github.com/uhulinux/ub-ubk2/commit/e00d57d2c21a854a1fdb4b64ad7bdbcbb49eeb1b
